### ISSUE TITLE
Brig CLI with Digital Ocean OAuth failing

### ISSUE THREAD

**Issue by TheTFo** [brigadecore/brigade#1057]
Output of `brig version`: v1.2.1

Output of `kubectl version`: 

Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): DigitalOcean

When using DigitalOcean K8s, I use their doctl tool to create my kube config. This seems to work fine with kubectl, however, with brig CLI I get this:

```
~ brig check
error: exec plugin: invalid apiVersion "client.authentication.k8s.io/v1beta1"
```

I can get around this issue by downloading a temporary kubeconfig that uses a certificate, however, I'd need to repeat this step every 7 days which isn't ideal.

Any ideas on what may going on here?

**Comment by krancour** [comment]
@TheTFo could you possibly share relevant sections of your kube config __with sensitive details redacted, obviously__?

I am guessing that the k8s go-client library we're using might _possibly_ be too old to support newer authentication mechanisms. Just a hunch.

**Comment by TheTFo** [comment]
I'll get you that this evening, thanks!!

**Comment by TheTFo** [comment]
I redacted aggressively, however, here's the problematic config, the working version does NOT contain the exec portion:

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <redacted>
    server: <redacted>
  name: <redacted>
contexts:
- context:
    cluster: <redacted>
    user: <redacted>
  name: <redacted>
current-context: <redacted>
kind: Config
preferences: {}
users:
- name: <redacted>
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - kubernetes
      - cluster
      - kubeconfig
      - exec-credential
      - --version=v1beta1
      - --context=default
      - <redacted>
      command: doctl
      env: null
```
