### ISSUE TITLE
gitlab-runner sometimes cannot detect the brig command failed 

### ISSUE THREAD

**Issue by kenotsolutions** [brigadecore/brigade#1088]
I run brig command in an image which runs in gitlab-runner.  Sometimes even the job fails the gitlab-runner says the job finished successfully but sometimes it catches the error and says the job failed.  I don't know how much is related to brig but somehow the gitlab-runner never gives the wrong message when I use docker-compose. 

gitlab-ci.yaml 

test_job:
  stage: test-stage
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: "/certs/client"
  services:
    - name: docker:stable-dind
 script:
    - docker run  private-repo-baseinstaller:v-1 brig run --no-progress -e test -f brigade.js -p payload.json test-project-name -n brigade
  

Output of `brig version`: 1.40

Output of `kubectl version`: 1.18

Cloud Provider/Platform (AKS, GKE, Minikube etc.): bare-metal

**Running after_script
Saving cache
Uploading artifacts for successful job
Job succeeded**

`
kubectl get pods -n brigade  |grep Error
brigade-worker-01eacvfy2dyzakbbfd6vwdy416              0/1     Error       0          74m
test-job-01eacvfy2dyzakbbfd6vwdy416   0/1     Error       0          75m
`

**Comment by kenotsolutions** [comment]
Hi,

sometimes I get the same error so it not related to extra layers 

gitlab-ci.yaml

```
test_master_job:
  stage: test_statge
  tags:
    - tasks-k8
  variables:
    DOCKER_DRIVER: overlay2
  services:
    - name: docker:stable-dind
  before_script:
    - apk add --no-cache make screen 
  script:
    -  	brig run --no-progress -e test_script  -f brigade.js -p / payload.json -r $(CI_COMMIT_REF_NAME) test-project -n brigade

kubectl get pods -n brigade
test-job-01eax0my1hesqcn2vj4z3v70a3   0/1     Error        0          65m

```

"test_master_job" creates multiple sub-jobs, create images and pushes to a private repo.  

```

async function createImages(event, project) {
 
  const {Group } = require("brigadier");
  try {
    const a = new create_master_images_job("a",event,project);
    const b = new create_master_images_job("b",event,project);
    const c = new create_master_images_job("c",event,project);
    const d = new create_master_images_job("d",event,project);
    Group.runAll([a,b,c,e])
  } catch (error) {
    logError(error);
  } 
}

class create_master_images_job extends Job {
 
  constructor(name, event, project) {
    try {
       super(name, INSTALLER_IMAGE);
      this.tasks = [
        ---
        "echo finished successfully",
        "echo =================================",
    
       ];
       
    } catch (error) {
      logError(error);
    }
  }
} 
```

Job succeeded
![image](https://user-images.githubusercontent.com/55690915/84715918-ca60f480-af69-11ea-8412-a2f2044f269e.png)

ERROR
![image](https://user-images.githubusercontent.com/55690915/84716040-085e1880-af6a-11ea-86ea-a27c5d39f362.png)
