### ISSUE TITLE
Kubernetes CD is failing with error "deployments.apps is forbidden"

### ISSUE THREAD

**Issue by abinashkd** [brigadecore/brigade#1121]
I have configured a job in brigade.js, which is as below:

```js
events.on("build-done", (e, project) => {
  console.log("Deploying to cluster")

  var deploy = new Job("deploy-runner", "bitnami/kubectl:latest")

  deploy.tasks = [
	"cd /src",
    "kubectl apply -f deploy.yaml"
  ]

  deploy.run().then( () => {
    events.emit("success", e, project)
  })
})
```

It is failing with below error:

```
Error from server (Forbidden): error when retrieving current configuration of:
Resource: "apps/v1, Resource=deployments", GroupVersionKind: "apps/v1, Kind=Deployment"
Name: "brigade-demo-app", Namespace: "default"
from server for: "deploy.yaml": deployments.apps "brigade-demo-app" is forbidden: User "system:serviceaccount:default:brigade-worker" cannot get resource "deployments" in API group "apps" in the namespace "default"
```

Deployment Yaml:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: brigade-demo-app
  labels:
    app: brigade-demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: brigade-demo-app
  template:
    metadata:
      labels:
        app: brigade-demo-app
    spec:
      imagePullSecrets:
      - name: **
      containers:
      - args:
        - -c
        image: **.azurecr.io/brigade-demo-app:latest
        imagePullPolicy: ""
        name: brigade-java-test
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "250m"
          limits:
            cpu: "500m"
      restartPolicy: Always
      serviceAccountName: "brigade-worker"
status: {}
```

Output of `brig version`: v1.4.0

Output of `kubectl version`: Major:"1", Minor:"18"

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AKS
