### ISSUE TITLE
Docs: Netlify site config

### ISSUE THREAD

**Issue by vdice** [brigadecore/brigade#1499]
@carolynvs recommends storing basic Netlify config in this repo itself, via a [netlify.toml config file](https://docs.netlify.com/configure-builds/file-based-configuration/), which allows us to fine-tune rules per branch (especially helpful during this v2 transition) and codifies the config rather than being managed via the Netlify site itself.

**Comment by EDDYMENS** [comment]
@krancour is it possible to point to some or any of the configs that are currently set via the Netlify GUI?

**Comment by krancour** [comment]
@EDDYMENS unfortunately, it's not possible. Our static sites are, as of recently, under CNCF's Netlify account and they've only given access out to each project's maintainers.

In light of that, I suppose the help-wanted label probably needs to be dropped from this issue.

**Comment by carolynvs** [comment]
In case it's helpful here is an example of settings that we've moved into our netlify.toml file

```toml
[settings]
  ID = "porter"

[build]
  publish = "docs/public"
  command = "make docs"

[build.environment]
  HUGO_VERSION = "0.78.1"

[context.branch-deploy]
  command = "make docs BASEURL=https://${BRANCH/\//-}.porter.sh/"
  
[context.deploy-preview]
  command = "make docs BASEURL=$DEPLOY_PRIME_URL/"
```
