### ISSUE TITLE
Support event handlers that run on all types for a given event source

### ISSUE THREAD

**Issue by vdice** [brigadecore/brigade#1627]
Currently, projects can subscribe to all types of events from a given source, e.g.

```yaml
spec:
  eventSubscriptions:
  - source: brigade.sh/cli
    types:
    - "*"
```

However, Brigade doesn't appear to support similar for event handlers, i.e. the following doesn't work yet:

```javascript
        events.on("brigade.sh/cli", "*", async event => {})
```

I propose Brigade should support declaring event handlers with type of `"*"`, which would then run on any type of event for a given source.
