### ISSUE TITLE
Projects with arbitrary embedded scripts

### ISSUE THREAD

**Issue by vdice** [brigadecore/brigade#1654]
We should add an example of a project wherein arbitrary scripts are embedded via `defaultConfigFiles` and then used within the Brigade script for the project.  This could be an additional example project and/or a doc example, say, in the [Advanced Scripting Guide](https://v2--brigade-docs.netlify.app/topics/scripting/advanced/) (Note: there is currently a [PR in flight updating this doc](https://github.com/brigadecore/brigade/pull/1653)).

There are two usages I can envision showing: directly by the worker and by jobs spawned by the worker.  However, I'm not sure if the latter is supported yet.

For the latter, I was thinking an example of a job accessing a helper script might look like the following.  However, it doesn't appear to work (`/share/sleep.sh` doesn't exist in the job's container).  Perhaps @krancour could advise.

```yaml
apiVersion: brigade.sh/v2-beta
kind: Project
metadata:
  id: misc-scripts
description: A project that demonstrates using misc embedded scripts
spec:
  eventSubscriptions:
  - source: brigade.sh/cli
    types:
    - "exec"
  workerTemplate:
    useWorkspace: true
    defaultConfigFiles:
      sleep.sh: |-
        #!/bin/bash
        sleep 45
      brigade.js: |-
        const { events, Job } = require("@brigadecore/brigadier");

        events.on("brigade.sh/cli", "exec", async event => {
          let job = new Job("job", "alpine:3.14", event);
          job.primaryContainer.workspaceMountPath = "/share"
          job.primaryContainer.command = ["/share/sleep.sh"];

          await job.run();
        });

        events.process();
```
