### ISSUE TITLE
PROPOSAL: Support multiple gateway configs in brigade-project values.yaml

### ISSUE THREAD

**Issue by technosophos** [brigadecore/brigade#197]
Right now, we have some configuration directives for the GitHub gateway in the brigade project values.yaml. This proposal is to make that mechanism flexible enough to handle arbitrary gateways.

What if we restructured the values.yaml to look like this:

```yaml
# regular stuff
disableFoo: false

# stuff that is available to the brigade.sh
secrets:
  foo: bar

## THIS IS THE NEW PART
# gateway-specific settings
gateways:
  github:
    token: 1234567890
  trello:
    secret: 0987665
  # ...
```

Gateways will then be able to access their specific configs using the dotted notation we currently use: `secret.data["gateways.trello.secret"]` (syntax being language-dependent, of course).
