### ISSUE TITLE
brigade-k8s-gateway resource types

### ISSUE THREAD

**Issue by tylerauerbeck** [brigadecore/brigade#414]
I'm looking to start building pipelines based off of different types of events occurring within my k8s cluster. I see that currently the brigade-k8s-gateway is configured to listen to pod and node events (based upon the following note in the values.yaml file:

`kind: (Pod or Node) - the Kubernetes kind. Events are only emitted for pod and node. `

Is there a specific reason for this? Or is this just waiting for further events to be supported? I'd be happy to start looking into some of this, but wanted to see if there were any details around it only being configured for these two at this point.

**Comment by technosophos** [comment]
I believe I removed that restriction in the last release, and it now emits all Kubernetes events. I need to go update that YAML file.

**Comment by technosophos** [comment]
What `filters` are you using in the `values.yaml` overrides? Those are what control which events actually percolate.

I've found that a decent way of learning which events to filter is to start up the k8s event gateway, then tail the gateway logs with `kubectl logs -f $GATEWAY_POD`. Then do some stuff in Kubernetes. The log output is _really_ verbose because of all the events that get generated.

Here's an example of one of my `values.yaml` files for the gateway. It's set up to watch for SuccessfulCreate off of a StatefulSet. I'm trying to find the one I had to monitor deployments. If I find it, I'll drop it in here too.

```yaml
# Set this to true to enable Kubernetes RBAC support (recommended)
rbac:
  enabled: false

# Image configuration
registry: deis
name: brigade-k8s-gateway
tag: latest
pullPolicy: "IfNotPresent"

# What to watch
project: brigade-3749267c302b7c43ff182a8cd629f9eb680678048895fd474a40f2

# Define the filters that you want to run.
# Filters are evaluated in order (top to bottom). Every filter must either
# 'accept' or 'reject' an event. The final rule is the default rule, and
# is typically merely of the form '- action: accept' or '- action: reject'
#
# The keys you can use in a filter are:
# - kind: (Pod or Node) - the Kubernetes kind. Events are only emitted for pod and node.
# - namespace: (Pod only) - the namespace to listen to
# - action: (reject, accept) - whether to accept or reject the event. If it is rejected, no Brigade build is started
# - reasons: (Killing, Starting, ...) - a list of reasons that you want to listen for.
#   Unfortunately, the precise list of reasons is not defined in Kubernetes.
#
# THESE ARE EXAMPLES.
# Our suggestion is that you ALWAYS set up Brigade in its own namespace, and
# then `reject` on any pod event in that namespace. Otherwise each time you
# trigger a build or job it will trigger another event, which will trigger another
# build, which will trigger another build, which will trigger another build....
filters:
  # Ignore all events coming from kube-system
  - namespace: kube-system
    action: reject
  - kind: StatefulSet
    action: accept
    reasons:
      - SuccessfulCreate
  # Reject anything else (don't DOS yourself)
  - action: reject
```
