### ISSUE TITLE
imagePullSecrets for vcsSidecar

### ISSUE THREAD

**Issue by LittleColin** [brigadecore/brigade#949]
Does a custom vcsSidecar allow imagePullSecrets to be specified?

I can see that the worker does as it has a structure:

```
worker:
   imagePullSecrets: mysecret
   registry: ...
   etc.
```

But the vcsSidecar appears to be just a name/value pair:
`
vcsSidecar: myregistry/myimage:tag
`
